"""initial

Revision ID: 1082fa06f220
Revises: 
Create Date: 2026-03-20 18:44:27.127832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1082fa06f220'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkingaccount', schema=None) as batch_op:
        batch_op.alter_column('limit',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('withdrawal_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_checkingaccount_account_id_account'), 'account', ['account_id'], ['id'])
        batch_op.drop_column('number')
        batch_op.drop_column('branch')
        batch_op.drop_column('balance')

    with op.batch_alter_table('individualclient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_individualclient_client_id_client'), 'client', ['client_id'], ['id'])
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individualclient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_individualclient_client_id_client'), type_='foreignkey')
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('client_id')

    with op.batch_alter_table('checkingaccount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('branch', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('number', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_checkingaccount_account_id_account'), type_='foreignkey')
        batch_op.alter_column('withdrawal_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('limit',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
