"""add user table

Revision ID: a23311b9398a
Revises: fecd3d9a35d5
Create Date: 2026-03-24 15:16:36.910433

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a23311b9398a"
down_revision: str | Sequence[str] | None = "fecd3d9a35d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
