"""remove relationships

Revision ID: fecd3d9a35d5
Revises: 1082fa06f220
Create Date: 2026-03-21 19:43:55.461548

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "fecd3d9a35d5"
down_revision: str | Sequence[str] | None = "1082fa06f220"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
